### ISSUE TITLE
Possibility to also capture vexes

### ISSUE THREAD

**Issue by 2mal3** [2mal3/Allay-in-a-Bottle#3]

**Comment by giggity404** [comment]
I think for this to make sense we'd have to add a vex to allay conversion mechanic along with it, I remember when allays were introduced ppl assumed you'd be able to convert them, since they're basically the same creature, & the suggestion shows up regularly on r/minecraftsuggestions, since wandering around for an outpost which has allays & going to a mansion is so time consuming

**Comment by giggity404** [comment]
I think a dun did it. Can have a look & give it a test run
I didn't want to have two versions of everything for vex & allay, so there's many if/else statements to distinguish along the way

https://user-images.githubusercontent.com/54961025/202574310-a9ba8c57-25fd-43c9-8c20-96a3b70d40fc.mp4

**Comment by 2mal3** [comment]
You are so fast :)
You can make a pull request again, so I can take a look. I'll work on the texture soon
